Master
ivanguk10/TrainingTimer pull request #1
Opened 2021-01-28 11:37 UTC by ivanguk10

2021-01-28 11:44 UTC, gmltA requested changes
So you converted the lab from someone else to Kotlin to pass...
Well, let's see what else can you do.

2021-01-28 11:44 UTC, gmltA commented on app/src/main/java/com/example/tabatatimer/SettingsActivity.kt
> +                if (value.toString() == "English" || value.toString() == "Английский") {
Convert string literals to enums.

2021-01-28 11:44 UTC, gmltA commented on app/src/main/java/com/example/tabatatimer/SettingsActivity.kt
> +                if (value.toString() == "Малый" || value.toString() == "Small") {
Convert string literals to enums.

2021-01-28 11:44 UTC, gmltA commented on app/src/main/java/com/example/tabatatimer/TrainingActivity.kt
> +                    if (status == "1") {
Convert string literals to enums.

2021-02-03 14:07 UTC, gmltA requested changes

2021-02-03 14:07 UTC, gmltA commented on app/src/main/java/com/example/tabatatimer/enums/Language.kt
> +    RUS("ru")
You have only two languages, so this enum should contain only two values.

2021-02-05 18:07 UTC, gmltA requested changes
I don't think this will compile.

2021-02-05 19:06 UTC, ivanguk10 commented
It is working

2021-02-05 19:16 UTC, ivanguk10 commented
Из интересного стоит отметить аттрибуты entries и entryValues у ListPreference. entries – это то, что отобразит список пользователю, а entryValues – это то, что сохранит система после выбора значения в списке.

2021-02-10 17:44 UTC, gmltA commented
`import com.example.tabatatimer.enums.Setting`

Я не бачу, адкуль вы вось гэта бярэце.

2021-02-10 18:03 UTC, ivanguk10 commented
Почему-то не залился этот enum class
![image](https://user-images.githubusercontent.com/48579825/107551507-68818900-6be3-11eb-896e-65779c1244f6.png)

2021-02-10 18:04 UTC, ivanguk10 commented
Добавил

2021-02-11 13:46 UTC, gmltA approved these changes

2021-04-13 16:08 UTC, closed without merging